# Generated by Django 4.2.6 on 2024-05-28 17:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=30)),
                ('applicant_relation', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('date_of_death', models.DateField()),
                ('deceased_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('deceased_fname', models.CharField(max_length=30)),
                ('deceased_mname', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('death_age', models.IntegerField()),
                ('cause_of_death', models.CharField(max_length=100)),
                ('deceased_address', models.CharField(max_length=50)),
                ('date_of_issue', models.DateTimeField(default=datetime.datetime(2024, 5, 28, 22, 58, 12, 104514))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_mail', models.EmailField(max_length=254)),
                ('c_mssg', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compl_type', models.CharField(max_length=30)),
                ('compl_loc', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 5, 28, 22, 58, 12, 104514))),
                ('desc', models.CharField(max_length=300)),
                ('document', models.ImageField(default='', upload_to='')),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Incomplete', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('gen', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(max_length=30)),
                ('dis_name', models.CharField(max_length=30)),
                ('place_of_bir', models.CharField(max_length=30)),
                ('bp_address', models.CharField(max_length=30)),
                ('c_address', models.CharField(max_length=30)),
                ('p_address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('num', models.IntegerField()),
                ('m_edu', models.CharField(max_length=30)),
                ('m_occ', models.CharField(max_length=30)),
                ('f_edu', models.CharField(max_length=30)),
                ('f_occ', models.CharField(max_length=30)),
                ('m_age_mar', models.IntegerField()),
                ('m_age_del', models.IntegerField()),
                ('date', models.DateField()),
                ('appli_name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
